### ISSUE TITLE
Instructor checklist onboarding process

### ISSUE THREAD

**Issue by mariehooper** [UM-USElab/gradecraft-development#2563]
This PR will implement the checklist portion of the instructor onboarding process. It's contingent upon the merge of issue #2596 
## Specifics:
- [ ] Add checklist widget that contains links to items/pages as shown (additional items are dependent on features selected on Basic Settings tab and should be added to checklist)
- [ ] User should be able to check items off as they have completed them and this should persist until they have published the course.
- [ ] Checklist will push sidebar content down so whole nav is still accessible to user
- [ ] Progress bar at top of checklist widget should show graphical representation of completed/total to-do items and should update as features are enabled (i.e. badges, challenges, multipliers, etc).
- [ ] Add ribbon to top of page that states that course is in unpublished state (this needs to be a new published boolean field on the Course model). Instructor will publish course when course setup is deemed complete and then it will be available to students. Until then, students should get a page with an 'under construction' type of message.
## Design

![instructor-onboarding-checklist](https://cloud.githubusercontent.com/assets/12573921/19657624/ff472c7c-99f2-11e6-8898-97860ac0a7ed.png)
