### ISSUE TITLE
standardize group and individual grading views

### ISSUE THREAD

**Issue by acousticrobot** [UM-USElab/gradecraft-development#2750]
Group Individual Grading forms are similar but not the same. Additionally, standard and rubric grading share some Angular features but are not fully aligned. This means any feature changes to the grading form requires four separate changes to be implemented in order to cover all four scenarios (group/rubric, group/standard, individual/rubric and individual/standard).

The shared components for these grading forms should be refactored to reuse the same architecture and code. This will make it easier to implement the following features:

  * autosave text feedback for group/standard grades (#2748)
  * grade next for group/rubric grades
  * badges for group grades (future feature, not yet requested)
  * file attachments for group grades (#2498)
  * auto-saving rubric criteria levels for individuals and groups (#2718)

**Comment by acousticrobot** [comment]
## Tasks, Initial PR:

- [ ] Standard grading
- [ ] pass/fail grading
- [ ] grade-level grading
- [ ] Auto-save for grades, and for criterion grades
- [ ] group grading, current functionality
- [ ] Rubric grading through the new Angular service
- [ ] build/test group rubric grading 
- [ ] restyling from new design specs
- [ ] add adjustment points to all grades
- [ ] remove custom value with score levels

## Tasks, Later PRs:

- [ ] add new front/back-end functionality and plan for grade "release" workflow
- [ ] review group grade and customizing single grades workflow
- [ ] review updates to grade when autosaving criterion grades (recalculate points each time?)
- [ ] better routing for grade and criterion grade autosave and submit actions
- [ ] review the service workflow for submitting/saving a grade
- [ ] review the process of updating a visible grade
